services:
  - type: web
    name: school-java-app
    plan: free
    runtime: docker
    branch: master
    buildCommand: ./mvnw package
    startCommand: java -jar target/parasi-0.0.1-SNAPSHOT.jar
    autoDeploy: true
