services:
  - type: web
    name: school-java-app
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/parasi-0.0.1-SNAPSHOT.jar
    branch: master
    autoDeploy: true