services:
  - type: web
    name: my-java-app
    runtime: java
    build:
      command: "./mvnw clean package"
    env: java
    envVars:
      - key: JAVA_VERSION
        value: 17
    startCommand: "java -jar target/parasi-0.0.1-SNAPSHOT.jar"